package orm.pojos;
// Generated 8 mar. 2021 19:33:56 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aula generated by hbm2java
 */
@Entity
@Table(name = "aula", catalog = "incidencias")
public class Aula implements java.io.Serializable {

	private Integer idaula;
	private String descripcion;
	private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

	public Aula() {
	}

	public Aula(String descripcion, Set<Incidencia> incidencias) {
		this.descripcion = descripcion;
		this.incidencias = incidencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idaula", unique = true, nullable = false)
	public Integer getIdaula() {
		return this.idaula;
	}

	public void setIdaula(Integer idaula) {
		this.idaula = idaula;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aula")
	public Set<Incidencia> getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set<Incidencia> incidencias) {
		this.incidencias = incidencias;
	}

}
