package orm.pojos;
// Generated 8 mar. 2021 19:33:56 by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.jfoenix.controls.datamodels.treetable.RecursiveTreeObject;

/**
 * Incidencia generated by hbm2java
 */
@Entity
@Table(name = "incidencia", catalog = "incidencias")
public class Incidencia extends RecursiveTreeObject<Incidencia> implements java.io.Serializable {

	private Integer idincidencia;
	private Aula aula;
	private Departamento departamento;
	private Estado estado;
	private Profesor profesorByResponsableSolucion;
	private Profesor profesorByProfesorIdprofesor;
	private Tipo tipo; //
	private Date fechaIncidencia;
	private Date fechaIntroduccion;
	private String descripcion;
	private String observaciones;
	private Date fechaResolucion;
	private Integer tiempoResolucion;
	private byte[] informacion;
	private Set<InfoHardware> infoHardwares = new HashSet<InfoHardware>(0);

	public Incidencia() {
	}

	public Incidencia(Aula aula, Departamento departamento, Estado estado, Profesor profesorByProfesorIdprofesor,
			Tipo tipo) {
		this.aula = aula;
		this.departamento = departamento;
		this.estado = estado;
		this.profesorByProfesorIdprofesor = profesorByProfesorIdprofesor;
		this.tipo = tipo;
	}

	public Incidencia(Aula aula, Departamento departamento, Estado estado, Profesor profesorByResponsableSolucion,
			Profesor profesorByProfesorIdprofesor, Tipo tipo, Date fechaIncidencia, Date fechaIntroduccion,
			String descripcion, String observaciones, Date fechaResolucion, Integer tiempoResolucion,
			byte[] informacion, Set<InfoHardware> infoHardwares) {
		this.aula = aula;
		this.departamento = departamento;
		this.estado = estado;
		this.profesorByResponsableSolucion = profesorByResponsableSolucion;
		this.profesorByProfesorIdprofesor = profesorByProfesorIdprofesor;
		this.tipo = tipo;
		this.fechaIncidencia = fechaIncidencia;
		this.fechaIntroduccion = fechaIntroduccion;
		this.descripcion = descripcion;
		this.observaciones = observaciones;
		this.fechaResolucion = fechaResolucion;
		this.tiempoResolucion = tiempoResolucion;
		this.informacion = informacion;
		this.infoHardwares = infoHardwares;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idincidencia", unique = true, nullable = false)
	public Integer getIdincidencia() {
		return this.idincidencia;
	}

	public void setIdincidencia(Integer idincidencia) {
		this.idincidencia = idincidencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aula_idaula", nullable = false)
	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento_iddepartamento", nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado_idestado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "responsable_solucion")
	public Profesor getProfesorByResponsableSolucion() {
		return this.profesorByResponsableSolucion;
	}

	public void setProfesorByResponsableSolucion(Profesor profesorByResponsableSolucion) {
		this.profesorByResponsableSolucion = profesorByResponsableSolucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profesor_idprofesor", nullable = false)
	public Profesor getProfesorByProfesorIdprofesor() {
		return this.profesorByProfesorIdprofesor;
	}

	public void setProfesorByProfesorIdprofesor(Profesor profesorByProfesorIdprofesor) {
		this.profesorByProfesorIdprofesor = profesorByProfesorIdprofesor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_idtipo", nullable = false)
	public Tipo getTipo() {
		return this.tipo;
	}

	public void setTipo(Tipo tipo) {
		this.tipo = tipo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_incidencia", length = 19)
	public Date getFechaIncidencia() {

		return fechaIncidencia;
	}

	public void setFechaIncidencia(Date fechaIncidencia) {
		this.fechaIncidencia = fechaIncidencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_introduccion", length = 19)
	public Date getFechaIntroduccion() {
		return this.fechaIntroduccion;
	}

	public void setFechaIntroduccion(Date fechaIntroduccion) {
		this.fechaIntroduccion = fechaIntroduccion;
	}

	@Column(name = "descripcion", length = 16777215)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "observaciones", length = 16777215)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_resolucion", length = 19)
	public Date getFechaResolucion() {
		return this.fechaResolucion;
	}

	public void setFechaResolucion(Date fechaResolucion) {
		this.fechaResolucion = fechaResolucion;
	}

	@Column(name = "tiempo_resolucion")
	public Integer getTiempoResolucion() {
		return this.tiempoResolucion;
	}

	public void setTiempoResolucion(Integer tiempoResolucion) {
		this.tiempoResolucion = tiempoResolucion;
	}

	@Column(name = "informacion")
	public byte[] getInformacion() {
		return this.informacion;
	}

	public void setInformacion(byte[] informacion) {
		this.informacion = informacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "incidencia")
	public Set<InfoHardware> getInfoHardwares() {
		return this.infoHardwares;
	}

	public void setInfoHardwares(Set<InfoHardware> infoHardwares) {
		this.infoHardwares = infoHardwares;
	}

	@Override
	public String toString() {

		return "\n\tTipo de incidencia: " + this.tipo.getTipo() + "\n\tProfesor que la creó: "
				+ this.profesorByProfesorIdprofesor.toString() + "\n\tFecha de creación:  " + this.fechaIncidencia
				+ "\n\tProfesor encargado de resolverla: " + this.profesorByResponsableSolucion + "\n\tEstado: "
				+ this.estado.getNombre() + "\n\tDepartamento: " + this.departamento.getNombre() + "\n\tAula: "
				+ this.aula.getDescripcion() + "\n\tDescripción: " + this.descripcion + "\n\tTiempo de resolución: "
				+ this.tiempoResolucion;
	}

}
