package orm.pojos;
// Generated 8 mar. 2021 19:33:56 by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InfoHardware generated by hbm2java
 */
@Entity
@Table(name = "info_hardware", catalog = "incidencias")
public class InfoHardware implements java.io.Serializable {

	private Integer idtipoHardware;
	private Incidencia incidencia;
	private TipoHarware tipoHarware;
	private String modelo;
	private String numeroSerie;

	public InfoHardware() {
	}

	public InfoHardware(Incidencia incidencia, TipoHarware tipoHarware) {
		this.incidencia = incidencia;
		this.tipoHarware = tipoHarware;
	}

	public InfoHardware(Incidencia incidencia, TipoHarware tipoHarware, String modelo, String numeroSerie) {
		this.incidencia = incidencia;
		this.tipoHarware = tipoHarware;
		this.modelo = modelo;
		this.numeroSerie = numeroSerie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipo_hardware", unique = true, nullable = false)
	public Integer getIdtipoHardware() {
		return this.idtipoHardware;
	}

	public void setIdtipoHardware(Integer idtipoHardware) {
		this.idtipoHardware = idtipoHardware;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_incidencia", nullable = false)
	public Incidencia getIncidencia() {
		return this.incidencia;
	}

	public void setIncidencia(Incidencia incidencia) {
		this.incidencia = incidencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_harware", nullable = false)
	public TipoHarware getTipoHarware() {
		return this.tipoHarware;
	}

	public void setTipoHarware(TipoHarware tipoHarware) {
		this.tipoHarware = tipoHarware;
	}

	@Column(name = "modelo", length = 45)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@Column(name = "numero_serie", length = 45)
	public String getNumeroSerie() {
		return this.numeroSerie;
	}

	public void setNumeroSerie(String numeroSerie) {
		this.numeroSerie = numeroSerie;
	}

}
