package orm.pojos;
// Generated 8 mar. 2021 19:33:56 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name = "profesor", catalog = "incidencias")
public class Profesor implements java.io.Serializable {

	private String dni;
	private Departamento departamento;
	private Rol rol;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String email;
	private String password;
	private Set<Incidencia> incidenciasForResponsableSolucion = new HashSet<Incidencia>(0);
	private Set<Incidencia> incidenciasForProfesorIdprofesor = new HashSet<Incidencia>(0);

	public Profesor() {
	}

	public Profesor(String dni, Departamento departamento, Rol rol, String nombre, String apellido1) {
		this.dni = dni;
		this.departamento = departamento;
		this.rol = rol;
		this.nombre = nombre;
		this.apellido1 = apellido1;
	}

	public Profesor(String dni, Departamento departamento, Rol rol, String nombre, String apellido1, String apellido2,
			String email, String password, Set<Incidencia> incidenciasForResponsableSolucion,
			Set<Incidencia> incidenciasForProfesorIdprofesor) {
		this.dni = dni;
		this.departamento = departamento;
		this.rol = rol;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.email = email;
		this.password = password;
		this.incidenciasForResponsableSolucion = incidenciasForResponsableSolucion;
		this.incidenciasForProfesorIdprofesor = incidenciasForProfesorIdprofesor;
	}

	@Id

	@Column(name = "dni", unique = true, nullable = false, length = 20)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento", nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_idrol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido1", nullable = false, length = 45)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "apellido2", length = 45)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 25)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profesorByResponsableSolucion")
	public Set<Incidencia> getIncidenciasForResponsableSolucion() {
		return this.incidenciasForResponsableSolucion;
	}

	public void setIncidenciasForResponsableSolucion(Set<Incidencia> incidenciasForResponsableSolucion) {
		this.incidenciasForResponsableSolucion = incidenciasForResponsableSolucion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profesorByProfesorIdprofesor")
	public Set<Incidencia> getIncidenciasForProfesorIdprofesor() {
		return this.incidenciasForProfesorIdprofesor;
	}

	public void setIncidenciasForProfesorIdprofesor(Set<Incidencia> incidenciasForProfesorIdprofesor) {
		this.incidenciasForProfesorIdprofesor = incidenciasForProfesorIdprofesor;
	}

	@Override
	public String toString() {
		return apellido1 + " " + apellido2 + ", " + nombre;
	}

}
