package orm.pojos;
// Generated 8 mar. 2021 19:33:56 by Hibernate Tools 5.0.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "incidencias")
public class Rol implements java.io.Serializable {

	private Integer idrol;
	private String descripcion;
	private Set<Profesor> profesors = new HashSet<Profesor>(0);
	private Set<RolPermiso> rolPermisos = new HashSet<RolPermiso>(0);

	public Rol() {
	}

	public Rol(String descripcion, Set<Profesor> profesors, Set<RolPermiso> rolPermisos) {
		this.descripcion = descripcion;
		this.profesors = profesors;
		this.rolPermisos = rolPermisos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idrol", unique = true, nullable = false)
	public Integer getIdrol() {
		return this.idrol;
	}

	public void setIdrol(Integer idrol) {
		this.idrol = idrol;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Profesor> getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set<Profesor> profesors) {
		this.profesors = profesors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<RolPermiso> getRolPermisos() {
		return this.rolPermisos;
	}

	public void setRolPermisos(Set<RolPermiso> rolPermisos) {
		this.rolPermisos = rolPermisos;
	}

	@Override
	public String toString() {

		return descripcion;
	}

}
