package orm.pojos;
// Generated 8 mar. 2021 19:33:56 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolPermiso generated by hbm2java
 */
@Entity
@Table(name = "rol_permiso", catalog = "incidencias")
public class RolPermiso implements java.io.Serializable {

	private RolPermisoId id;
	private Permiso permiso;
	private Rol rol;
	private byte boolean_;

	public RolPermiso() {
	}

	public RolPermiso(RolPermisoId id, Permiso permiso, Rol rol, byte boolean_) {
		this.id = id;
		this.permiso = permiso;
		this.rol = rol;
		this.boolean_ = boolean_;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "rolIdrol", column = @Column(name = "rol_idrol", nullable = false)),
			@AttributeOverride(name = "permisoIdpermiso", column = @Column(name = "permiso_idpermiso", nullable = false)) })
	public RolPermisoId getId() {
		return this.id;
	}

	public void setId(RolPermisoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "permiso_idpermiso", nullable = false, insertable = false, updatable = false)
	public Permiso getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Permiso permiso) {
		this.permiso = permiso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_idrol", nullable = false, insertable = false, updatable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "boolean", nullable = false)
	public byte getBoolean_() {
		return this.boolean_;
	}

	public void setBoolean_(byte boolean_) {
		this.boolean_ = boolean_;
	}

}
