package orm.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipo generated by hbm2java
 */
@Entity
@Table(name = "tipo", catalog = "incidencias")
public class Tipo implements java.io.Serializable {

	private Integer idtipo;
	private String tipo;
	private Set<Incidencia> incidencias = new HashSet<Incidencia>(0);

	public Tipo() {
	}

	public Tipo(String tipo) {
		this.tipo = tipo;
	}

	public Tipo(String tipo, Set<Incidencia> incidencias) {
		this.tipo = tipo;
		this.incidencias = incidencias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipo", unique = true, nullable = false)
	public Integer getIdtipo() {
		return this.idtipo;
	}

	public void setIdtipo(Integer idtipo) {
		this.idtipo = idtipo;
	}

	@Column(name = "tipo", nullable = false, length = 45)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipo")
	public Set<Incidencia> getIncidencias() {
		return this.incidencias;
	}

	public void setIncidencias(Set<Incidencia> incidencias) {
		this.incidencias = incidencias;
	}

	@Override
	public String toString() {
		return tipo;
	}

}
