package orm.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoHarware generated by hbm2java
 */
@Entity
@Table(name = "tipo_harware", catalog = "incidencias")
public class TipoHarware implements java.io.Serializable {

	private Integer idtipoHarware;
	private String nombre;
	private Set<InfoHardware> infoHardwares = new HashSet<InfoHardware>(0);

	public TipoHarware() {
	}

	public TipoHarware(String nombre, Set<InfoHardware> infoHardwares) {
		this.nombre = nombre;
		this.infoHardwares = infoHardwares;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtipo_harware", unique = true, nullable = false)
	public Integer getIdtipoHarware() {
		return this.idtipoHarware;
	}

	public void setIdtipoHarware(Integer idtipoHarware) {
		this.idtipoHarware = idtipoHarware;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoHarware")
	public Set<InfoHardware> getInfoHardwares() {
		return this.infoHardwares;
	}

	public void setInfoHardwares(Set<InfoHardware> infoHardwares) {
		this.infoHardwares = infoHardwares;
	}

	@Override
	public String toString() {
		return nombre;
	}

}
